/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas2;

import datos.Usuarios;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class ConsultarDatos extends javax.swing.JFrame {
     Usuarios usuario;
    /**
     * Creates new form ConsultarDatos
     */
    public ConsultarDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JTextField();
        CEDULA = new javax.swing.JTextField();
        CORREO = new javax.swing.JTextField();
        DIRECCION = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FECHA = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        Genero = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        HORA = new javax.swing.JTextField();
        botonGuadar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonbuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), "DATOS DE TRABAJADORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Direccion:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefono:");

        NOMBRE.setBackground(new java.awt.Color(255, 255, 255));
        NOMBRE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        NOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NOMBREKeyTyped(evt);
            }
        });

        APELLIDO.setBackground(new java.awt.Color(255, 255, 255));
        APELLIDO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        APELLIDO.setForeground(new java.awt.Color(0, 0, 0));
        APELLIDO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                APELLIDOKeyTyped(evt);
            }
        });

        CEDULA.setBackground(new java.awt.Color(255, 255, 255));
        CEDULA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CEDULA.setForeground(new java.awt.Color(0, 0, 0));
        CEDULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEDULAActionPerformed(evt);
            }
        });
        CEDULA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CEDULAKeyTyped(evt);
            }
        });

        CORREO.setBackground(new java.awt.Color(255, 255, 255));
        CORREO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CORREO.setForeground(new java.awt.Color(0, 0, 0));
        CORREO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CORREOFocusLost(evt);
            }
        });
        CORREO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CORREOKeyTyped(evt);
            }
        });

        DIRECCION.setBackground(new java.awt.Color(255, 255, 255));
        DIRECCION.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DIRECCION.setForeground(new java.awt.Color(0, 0, 0));
        DIRECCION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DIRECCIONKeyTyped(evt);
            }
        });

        TELEFONO.setBackground(new java.awt.Color(255, 255, 255));
        TELEFONO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TELEFONO.setForeground(new java.awt.Color(0, 0, 0));
        TELEFONO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TELEFONOKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/User_Menu-80_icon-icons.com_57244.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("fecha:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Genero:");

        Genero.setBackground(new java.awt.Color(255, 255, 255));
        Genero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Genero.setForeground(new java.awt.Color(0, 0, 0));
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer" }));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Hora:");

        HORA.setBackground(new java.awt.Color(255, 255, 255));
        HORA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HORA.setForeground(new java.awt.Color(0, 0, 0));
        HORA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HORAKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CEDULA)
                                    .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HORA, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CORREO)
                            .addComponent(DIRECCION, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TELEFONO)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(HORA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CORREO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        botonGuadar.setBackground(new java.awt.Color(255, 255, 255));
        botonGuadar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonGuadar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuadar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/restart_back_left_arrow_6022.png"))); // NOI18N
        botonGuadar.setText("atras");
        botonGuadar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuadarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuadarMouseExited(evt);
            }
        });
        botonGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuadarActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/delete-file_40456 (1).png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setEnabled(false);
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEliminarMouseExited(evt);
            }
        });
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(255, 255, 255));
        botonModificar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(0, 0, 0));
        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/pen_edit_modify_pencil_icon_181536.png"))); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setEnabled(false);
        botonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonModificarMouseExited(evt);
            }
        });
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/Cancel_icon-icons.com_73703.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCancelarMouseExited(evt);
            }
        });
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Clientes.png"))); // NOI18N
        jLabel7.setText("CONSULTAR DATOS TRABAJADORES");

        botonbuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonbuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonbuscar.setForeground(new java.awt.Color(0, 0, 0));
        botonbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/search_book_open_search_locate_6178 (1).png"))); // NOI18N
        botonbuscar.setText("Buscar");
        botonbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonbuscarMouseExited(evt);
            }
        });
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/people_114360 (2).png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/COCA_COLA.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG3/java_22523.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCancelar)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonbuscar)
                                .addGap(86, 86, 86)
                                .addComponent(botonModificar)
                                .addGap(56, 56, 56)
                                .addComponent(botonEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuadar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(237, 237, 237))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuadar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminar)
                            .addComponent(botonModificar)
                            .addComponent(botonCancelar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonbuscar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
      
        
         if(CEDULA.getText() == null || CEDULA.getText().isEmpty()){
             String msj = "Para modificar primero debe buscar un trabajador";
             JOptionPane.showMessageDialog(this, msj);
             limpiarCampos();
             return;
        }
        if(CEDULA.getText().equals(usuario.cedula) != true){
         String msj = "La cedula no coincide con cedula de trabajador";
             JOptionPane.showMessageDialog(this, msj);
             limpiarCampos();
             return;
        
        }
        this.usuario = Usuarios.usuariosBD.get(CEDULA.getText());
        String nombre = NOMBRE.getText();
        String apellido = APELLIDO.getText();
        String correo = CORREO.getText();
        String direccion = DIRECCION.getText();
        String telefono = TELEFONO.getText();
        String fecha = FECHA.getEditor() .getText();
        String hora = HORA.getText();
        
       this.usuario.nombre = nombre;
       this.usuario.apellido = apellido;
       this.usuario.correo = correo;
       this.usuario.direccion = direccion;
       this.usuario.telefono = telefono;
       this.usuario.fecha = fecha;
       this.usuario.hora = hora;
       Usuarios.usuariosBD.put(this.usuario.cedula, usuario);
       String msj = "Trabajador modificado con exito" ;
       JOptionPane.showMessageDialog(this, msj);
       limpiarCampos();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        // TODO add your handling code here:
          String cedula = CEDULA.getText();
        
        if(Usuarios.usuariosBD == null || Usuarios.usuariosBD.isEmpty()){
        String msj = "No exiten usuarios en la base de datos";
        JOptionPane.showMessageDialog(this, msj);
        }
        else{
            if(Usuarios.usuariosBD.containsKey(cedula)){
               this.usuario = Usuarios.usuariosBD.get(cedula);
               NOMBRE.setText(this.usuario.cedula);
               APELLIDO.setText(this.usuario.apellido);
               CORREO.setText(this.usuario.correo);
               DIRECCION.setText(this.usuario.direccion);
               NOMBRE.setText(this.usuario.nombre);
               TELEFONO.setText(this.usuario.telefono);
               FECHA.getEditor() .setText(this.usuario.fecha);
               HORA.setText(this.usuario.hora);
               botonModificar.setEnabled(true);
               botonEliminar.setEnabled(true);
            }
            else {
                String msj = "No existe un Trabajador con esa cedula " + cedula;
                JOptionPane.showMessageDialog(this, msj);
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
         int opcion = JOptionPane.showConfirmDialog(this, "¿Desea cerrar"
               , "OJO - CONFIRMAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
         this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
         if(CEDULA.getText() == null || CEDULA.getText().isEmpty()){
             String msj = "Para eliminar primero debe buscar un trabajador";
             JOptionPane.showMessageDialog(this, msj);
             limpiarCampos();
             return;
        }
        if(CEDULA.getText().equals(usuario.cedula) != true){
         String msj = "La cedula no coincide con cedula de trabajador";
             JOptionPane.showMessageDialog(this, msj);
             limpiarCampos();
             return;
        }
        String msj = "Seguro que desea eliminar este trabajador";
        int respuesta = JOptionPane.showConfirmDialog(this,msj,"CONFIMAR"
        ,JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respuesta == JOptionPane.YES_NO_OPTION){
         Usuarios.usuariosBD.remove(this.usuario.cedula);
         int total = Usuarios.usuariosBD.size();
         String msj2 = "Trabajador eliminado con exito\nTOTAL: "+total;
         JOptionPane.showMessageDialog(this, msj2);
         limpiarCampos();
         
        }
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuadarActionPerformed
        // TODO add your handling code here:
        RegistrarT registrar = new RegistrarT();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonGuadarActionPerformed

    private void botonGuadarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuadarMouseEntered
        // TODO add your handling code here:
        botonGuadar.setBackground(Color.GREEN);
    }//GEN-LAST:event_botonGuadarMouseEntered

    private void botonGuadarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuadarMouseExited
        // TODO add your handling code here:
        botonGuadar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botonGuadarMouseExited

    private void botonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseEntered
        // TODO add your handling code here:
         botonEliminar.setBackground(Color.RED);
    }//GEN-LAST:event_botonEliminarMouseEntered

    private void botonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseExited
        // TODO add your handling code here:
       botonEliminar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botonEliminarMouseExited

    private void botonModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseEntered
        // TODO add your handling code here:
         botonModificar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_botonModificarMouseEntered

    private void botonModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseExited
        // TODO add your handling code here:
        botonModificar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botonModificarMouseExited

    private void botonbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonbuscarMouseEntered
        // TODO add your handling code here:
       botonbuscar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_botonbuscarMouseEntered

    private void botonbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonbuscarMouseExited
        // TODO add your handling code here:
        botonbuscar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botonbuscarMouseExited

    private void botonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseEntered
        // TODO add your handling code here:
        botonCancelar.setBackground(Color.RED);
    }//GEN-LAST:event_botonCancelarMouseEntered

    private void botonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseExited
        // TODO add your handling code here:
        botonCancelar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botonCancelarMouseExited

    private void CEDULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEDULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEDULAActionPerformed

    private void CEDULAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CEDULAKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();;
           
           JOptionPane.showMessageDialog(rootPane, "Ingrese Solo Numeros");
        }
        if(CEDULA.getText().length() >=10 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_CEDULAKeyTyped

    private void DIRECCIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DIRECCIONKeyTyped
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();;
           
           JOptionPane.showMessageDialog(rootPane, "Ingrese Solo Numeros");
        }
        if(DIRECCION.getText().length() >=10 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_DIRECCIONKeyTyped

    private void NOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOMBREKeyTyped
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese Solo letras");
        
        }
        if(NOMBRE.getText().length() >=10 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_NOMBREKeyTyped

    private void APELLIDOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APELLIDOKeyTyped
        // TODO add your handling code here:
         char validar=evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese Solo letras");
        
        }
        if(APELLIDO.getText().length() >=10 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_APELLIDOKeyTyped
     public boolean isEmail(String correo){
      Pattern pat = null;
      Matcher mat = null;
      pat = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
      mat = pat.matcher(correo);
      if(mat.find()){
           return true;
      }else{
           return false;
      }
     }  
    private void CORREOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CORREOFocusLost
        // TODO add your handling code here:
         if(isEmail(CORREO.getText())){
        
        }else{
           JOptionPane.showMessageDialog(null, "Email incorrecto","Validar email",
                   JOptionPane.INFORMATION_MESSAGE);
           CORREO.requestFocus();
        }
    }//GEN-LAST:event_CORREOFocusLost

    private void HORAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HORAKeyTyped
        // TODO add your handling code here:
        if(HORA.getText().length() >=8 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_HORAKeyTyped

    private void CORREOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CORREOKeyTyped
        // TODO add your handling code here:
        if(CORREO.getText().length() >=20 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_CORREOKeyTyped

    private void TELEFONOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TELEFONOKeyTyped
        // TODO add your handling code here:
        if(TELEFONO.getText().length() >=20 ){
           evt.consume();
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TELEFONOKeyTyped
 public void limpiarCampos(){
       NOMBRE.setText("");
       APELLIDO.setText("");
       CEDULA.setText("");
       CORREO.setText("");
       DIRECCION.setText("");
       TELEFONO.setText("");
       FECHA.getEditor() .setText("");
       FECHA.getEditor() .setEditable(false);
       HORA.setText("");
       botonModificar.setEnabled(false);
       botonEliminar.setEnabled(false);
       
 }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APELLIDO;
    private javax.swing.JTextField CEDULA;
    private javax.swing.JTextField CORREO;
    private javax.swing.JTextField DIRECCION;
    private org.jdesktop.swingx.JXDatePicker FECHA;
    private javax.swing.JComboBox<String> Genero;
    private javax.swing.JTextField HORA;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField TELEFONO;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuadar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
