/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;


import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import ventana5.Novedades;
import ventana5.Producto;
import ventana7.ventanaLogin;
import ventanas.LongiGerencia;
import ventanas.VentanaPrincipal;

import ventanas3.IdTrabajadores;
import ventanas4.IdSupervisor;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
         this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gerencia = new javax.swing.JButton();
        supervisor = new javax.swing.JButton();
        ganacias = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        horarios = new javax.swing.JButton();
        trabajdores = new javax.swing.JButton();
        novedades = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        gerencia.setBackground(new java.awt.Color(255, 255, 255));
        gerencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gerencia.setForeground(new java.awt.Color(0, 0, 0));
        gerencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/administrator-icon.png"))); // NOI18N
        gerencia.setText("Gerencia");
        gerencia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gerenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gerenciaMouseExited(evt);
            }
        });
        gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaActionPerformed(evt);
            }
        });

        supervisor.setBackground(new java.awt.Color(255, 255, 255));
        supervisor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        supervisor.setForeground(new java.awt.Color(0, 0, 0));
        supervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Uptight-icon.png"))); // NOI18N
        supervisor.setText("Supervisor");
        supervisor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        supervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supervisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supervisorMouseExited(evt);
            }
        });
        supervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorActionPerformed(evt);
            }
        });

        ganacias.setBackground(new java.awt.Color(255, 255, 255));
        ganacias.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ganacias.setForeground(new java.awt.Color(0, 0, 0));
        ganacias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/support_call_center_help_information_customer_service_icon_140644.png"))); // NOI18N
        ganacias.setText("Ganacias");
        ganacias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ganacias.setInheritsPopupMenu(true);
        ganacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ganaciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ganaciasMouseExited(evt);
            }
        });
        ganacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganaciasActionPerformed(evt);
            }
        });

        producto.setBackground(new java.awt.Color(255, 255, 255));
        producto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        producto.setForeground(new java.awt.Color(0, 0, 0));
        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/coke_folder_file_10459.png"))); // NOI18N
        producto.setText("Producto");
        producto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productoMouseExited(evt);
            }
        });
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });

        horarios.setBackground(new java.awt.Color(255, 255, 255));
        horarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        horarios.setForeground(new java.awt.Color(0, 0, 0));
        horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG3/html_24069 (1).png"))); // NOI18N
        horarios.setText("Pagina");
        horarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        horarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                horariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                horariosMouseExited(evt);
            }
        });
        horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horariosActionPerformed(evt);
            }
        });

        trabajdores.setBackground(new java.awt.Color(255, 255, 255));
        trabajdores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        trabajdores.setForeground(new java.awt.Color(0, 0, 0));
        trabajdores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/groups_people_people_1715.png"))); // NOI18N
        trabajdores.setText("Trabajadores");
        trabajdores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        trabajdores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trabajdoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trabajdoresMouseExited(evt);
            }
        });
        trabajdores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajdoresActionPerformed(evt);
            }
        });

        novedades.setBackground(new java.awt.Color(255, 255, 255));
        novedades.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        novedades.setForeground(new java.awt.Color(0, 0, 0));
        novedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/notes_2_43442.png"))); // NOI18N
        novedades.setText("Novedades");
        novedades.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        novedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                novedadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                novedadesMouseExited(evt);
            }
        });
        novedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novedadesActionPerformed(evt);
            }
        });

        atras.setBackground(new java.awt.Color(255, 255, 255));
        atras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(0, 0, 0));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/restart_back_left_arrow_6022.png"))); // NOI18N
        atras.setText("Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMouseExited(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(supervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(trabajdores, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(ganacias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(horarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(novedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trabajdores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ganacias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novedades, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(255, 0, 0));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/coca cola 21 .png"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaActionPerformed
        // TODO add your handling code here:
       LongiGerencia login = new LongiGerencia();
       login.setVisible(true);
       dispose();
       
       
    }//GEN-LAST:event_gerenciaActionPerformed

    private void ganaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganaciasActionPerformed
        // TODO add your handling code here:
        ventanaLogin login = new ventanaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_ganaciasActionPerformed

    private void trabajdoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajdoresActionPerformed
        // TODO add your handling code here:
        IdTrabajadores id = new IdTrabajadores();
        id.setVisible(true);
        dispose();
    }//GEN-LAST:event_trabajdoresActionPerformed

    private void supervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorActionPerformed
        // TODO add your handling code here:
        IdSupervisor Id = new IdSupervisor();
        Id.setVisible(true);
        dispose();
    }//GEN-LAST:event_supervisorActionPerformed

    private void horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horariosActionPerformed
        // TODO add your handling code here:
          try {
            Desktop.getDesktop().browse(new URI("file:///C:/Users/USUARIO/Documents/Coca-cola/index.html"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Novedades.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_horariosActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
        Producto pt = new Producto();
        pt.setVisible(true);
        dispose();
    }//GEN-LAST:event_productoActionPerformed

    private void novedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novedadesActionPerformed
        // TODO add your handling code here:
       Novedades n = new Novedades();
       n.setVisible(true);
       dispose();
    }//GEN-LAST:event_novedadesActionPerformed

    private void gerenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciaMouseEntered
        // TODO add your handling code here:
        gerencia.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_gerenciaMouseEntered

    private void gerenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciaMouseExited
        // TODO add your handling code here:
        gerencia.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_gerenciaMouseExited

    private void trabajdoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajdoresMouseEntered
        // TODO add your handling code here:
        trabajdores.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_trabajdoresMouseEntered

    private void trabajdoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajdoresMouseExited
        // TODO add your handling code here:
        trabajdores.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_trabajdoresMouseExited

    private void supervisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supervisorMouseEntered
        // TODO add your handling code here:
        supervisor.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_supervisorMouseEntered

    private void supervisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supervisorMouseExited
        // TODO add your handling code here:
        supervisor.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_supervisorMouseExited

    private void ganaciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganaciasMouseEntered
        // TODO add your handling code here:
        ganacias.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_ganaciasMouseEntered

    private void ganaciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganaciasMouseExited
        // TODO add your handling code here:
        ganacias.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ganaciasMouseExited

    private void productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseEntered
        // TODO add your handling code here:
        producto.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_productoMouseEntered

    private void productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseExited
        // TODO add your handling code here:
        producto.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_productoMouseExited

    private void horariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosMouseEntered
        // TODO add your handling code here:
        horarios.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_horariosMouseEntered

    private void horariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosMouseExited
        // TODO add your handling code here:
        horarios.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_horariosMouseExited

    private void novedadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novedadesMouseEntered
        // TODO add your handling code here:
        novedades.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_novedadesMouseEntered

    private void novedadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novedadesMouseExited
        // TODO add your handling code here:
        novedades.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_novedadesMouseExited

    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        atras.setBackground(Color.GREEN);
    }//GEN-LAST:event_atrasMouseEntered

    private void atrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseExited
        // TODO add your handling code here:
        atras.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_atrasMouseExited

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton ganacias;
    private javax.swing.JButton gerencia;
    private javax.swing.JButton horarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton novedades;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton producto;
    private javax.swing.JButton supervisor;
    private javax.swing.JButton trabajdores;
    // End of variables declaration//GEN-END:variables
}
